// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYr_QHJdtSvkTpNRsJEeSaKkLdNhPtSI0',
    appId: '1:1017462574047:web:b06856a6697f610225526a',
    messagingSenderId: '1017462574047',
    projectId: 'kgiantmobile',
    authDomain: 'kgiantmobile.firebaseapp.com',
    storageBucket: 'kgiantmobile.appspot.com',
    measurementId: 'G-ND865K8QH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcGwwnkjtCeaB5DRhJG7DkQvr2z7Wftk',
    appId: '1:1017462574047:android:036b42e331c6cdab25526a',
    messagingSenderId: '1017462574047',
    projectId: 'kgiantmobile',
    storageBucket: 'kgiantmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvw1cbX97dKhySg-UVjNW4WiF5TmbSy_8',
    appId: '1:1017462574047:ios:3e46f4685c39a88725526a',
    messagingSenderId: '1017462574047',
    projectId: 'kgiantmobile',
    storageBucket: 'kgiantmobile.appspot.com',
    iosBundleId: 'com.example.kgiantmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvw1cbX97dKhySg-UVjNW4WiF5TmbSy_8',
    appId: '1:1017462574047:ios:ae36341685dcc0ec25526a',
    messagingSenderId: '1017462574047',
    projectId: 'kgiantmobile',
    storageBucket: 'kgiantmobile.appspot.com',
    iosBundleId: 'com.example.kgiantmobile.RunnerTests',
  );
}
